    modLoader="javafml"
    loaderVersion="[37,)"
    license="MIT"
    issueTrackerURL="https://github.com/Asatsuki/BetterDoT/issues"
    showAsResourcePack=false

    [[mods]]
      modId="betterdot"
      version="1.0.0.0"
      displayName="Better DoT"
      logoFile="logo.png"
      authors="Asatsuki256"
      description='''
Independent DoT invincible time
'''

    [[dependencies.betterdot]]
      modId="forge"
      mandatory=true
      versionRange="[37,)"
      ordering="NONE"
      side="BOTH"

    [[dependencies.betterdot]]
      modId="minecraft"
      mandatory=true
      versionRange="1.18)"
      ordering="NONE"
      side="BOTH"